// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaHD.DAL;

#nullable disable

namespace TiendaHD.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250311035910_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("TiendaHD.Models.Financiamientos", b =>
                {
                    b.Property<int>("FinanciamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CuotaMensual")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FinanciamientoId");

                    b.ToTable("Financiamientos");
                });
#pragma warning restore 612, 618
        }
    }
}
